### ISSUE TITLE
bug: can't install due to missing "version" field in manifest.json

### ISSUE THREAD

**Issue by ycnmhd** [Jamalam360/obsidian-automatic-tags#1]
I'm getting the following error when I try to install the plugin both from the community store and BRAT
![image](https://github.com/Jamalam360/obsidian-automatic-tags/assets/33285087/a6ad8882-a3c7-4ed1-a810-d12d9828d499)

**Comment by Jamalam360** [comment]
Hmm yeah for some reason the versions.json contains an `undefined` version instead of 1.1.0

**Comment by Jamalam360** [comment]
I just updated it. Please try again whenever but be aware there will be caching involved so it might not work still

**Comment by Jamalam360** [comment]
Just tested and for some reason the obsidian template provided `version-bump.mjs` seems to not be working. I've manually set the versions and released 1.1.1 which should work

**Comment by ycnmhd** [comment]
The plugin can be installed now. Thank you.

PS: You only need to update `versions.json` when you change `minAppVersion` in `manifest.json` (https://docs.obsidian.md/Reference/Versions#:~:text=user's%20Obsidian%20app.-,versions.,Obsidian%20looks%20for%20a%20versions.)
I personally update `package.json` and `manifest.json` manually when I release a new version of my plugins.
